apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-data-pv
  namespace: linkding
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  